# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Configure settings.xml for GitHub Packages
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "ht-common-lib",
              "username": "${{ github.actor }}",
              "password": "${{ github.token }}"
            },
            {
              "id": "ht-parent",
              "username": "${{ github.actor }}",
              "password": "${{ github.token }}"
            }]
          repositories: |
            [{
              "id": "ht-parent",
              "url": "https://maven.pkg.github.com/health-tracker-educational-project/health-tracker-parent"
            }]

      - name: Debug Maven settings
        run: cat /home/runner/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}